#!/usr/bin/env bash
#
# Wrzuta downloader v0.41
#
# Autor: Jakub 'samu' Szafrański
# irc:   samu @ irc.pirc.pl
#
# Syntax: ./wrzuta.sh artysta i tytuł piosenki
#
# Licencja: Creative Commons Uznanie autorstwa 3.0 Polska 
#

echo "Wrzuta downloader v0.4 by samu"
if [ "$1" == "" ]; then
   echo "Podaj nazwe piosenki jako pierwszy argument!";
   exit;
fi

tytul=`echo $1 | sed -e "s/ /+/g"`
adres=`curl -s http://www.wrzuta.pl/szukaj/audio/$tytul/ | grep '<a class="title"' | awk -F"/" '{print $3"/"$4"/"$5"/"$6}' | awk -F"\"" '{print $1}' | sed -e 's/" "/_/g' `

echo -e "Znalazlem nastepujace wyniki:"
TMPx=0;
for id in $adres; do
   songs[$TMPx]=$id;
   id=`echo $id | sed -e 's|.*/\(.*\)|\1|'`;
   echo -ne $TMPx;
   echo -ne ". $id\n";
   TMPx=$((TMPx+1));
done

echo -ne "\nWpisz numer piosenki do pobrania: ";
read songid

if [ "${songs[$songid]}" != "" ]; then
   echo ${songs[$songid]};
else
   echo "Nie ma takiej piosenki na liscie!";
   exit;
fi

html=`curl -s http://${songs[$songid]}`
key=`echo $html | egrep -o 'key=([A-Za-z0-9]+?)&amp;' |sed -e 's/key=\(.*\)&amp;/\1/'`;
login=`echo $html | egrep -o 'login=([A-Za-z0-9]+?)&amp;' |sed -e "s/login=\(.*\)&amp;/\1/"`;
fileid=`curl -s http://$login.wrzuta.pl/xml/plik/$key/wrzuta.pl/undefined/$RANDOM | egrep -o '<fileId><!\[CDATA\[(.*?)\]\]></fileId>' |sed -e 's/<fileId><!\[CDATA\[\(.*\)\]\]><\/fileId>/\1/'`;
wget -O `echo ${songs[$songid]} | awk -F"/" '{print $4".mp3"}'` $fileid;

